### ISSUE TITLE
Arch Linux, no side panel, only main browser window.

### ISSUE THREAD

**Issue by mikedebian** [roblillack/fsviewer#4]
FSViewer found all libs during compile, no errors, installed succesfully.

Main browser mode window opens. Can click around, launch files, enter folders, drag folders to the top to bookmark.
No side panel, can not manipulate files other than launch.

Based on the screenshot in the README file, that is not the intended way as far as I understand.

-- Checking for modules 'wrlib;wmlib;WUtil;WINGs;xpm;xmu;x11'
--   Found wrlib, version 0.95.9
--   Found wmlib, version 0.95.9
--   Found WUtil, version 0.95.9
--   Found WINGs, version 0.95.9
--   Found xpm, version 3.5.14
--   Found xmu, version 1.1.4
--   Found x11, version 1.8.3

No errors outputted while running application. All files installed where they should be.

Using Windowmaker-crm-git, compiled 12 september 2022.

**Comment by roblillack** [comment]
Hey @mikedebian, this sounds a lot like an issue with WindowMaker's configuration, see for example https://github.com/roblillack/wmaker/pull/4. Can you try adapting your configuration and restart wmaker?

**Comment by mikedebian** [comment]
Hello, yes I can try, however to let you know, app menu works in all other gnustep applications I have installed.

**Comment by mikedebian** [comment]
I made the change to the source file, installed modified file, did not have any effect, sorry.

**Comment by mikedebian** [comment]
Today, it suddenly wanted to work. No changes made in any windowmaker files, no nothing. Very weird. I just opened it up and there the pane was.

**Comment by Strahinja** [comment]
I'm having this issue on the latest Alpine Linux (3.18), using latest packages, FSViewer built from fresh git clone. Modifying _/etc/WindowMaker/WMWindowAttributes_ doesn't help, menu isn't shown and I can only use the window title context menu item "Kill" to close FSViewer. I have attached the relevant files here:

Contents of _/etc/WindowMaker/WMWindowAttributes_:
```
{
  Logo.WMDock = {Icon = GNUstepGlow.tiff;};
  Logo.WMPanel = {Icon = GNUstep.tiff;};
  Logo.WMClip = {Icon = clip.tiff;};
  WMDrawer = {Icon = Drawer.tiff;};
  "*" = {Icon = defaultAppIcon.tiff;};
}
```

[CMakeCache.txt](https://github.com/roblillack/fsviewer/files/13056687/CMakeCache.txt)
[install_manifest.txt](https://github.com/roblillack/fsviewer/files/13056688/install_manifest.txt)
