### ISSUE TITLE
Translation files not installed?

### ISSUE THREAD

**Issue by Strahinja** [roblillack/fsviewer#5]
It seems that with the current main branch, cmake doesn't install any _.g?mo_ files nor does it compile _.po_ files. In fact, _.gmo_ files just seem to be included in the repository, which also shouldn't be the case. The only files installed are the binary, by default _/usr/local/bin/FSViewer_, and _.xpm_ and _.tif_ icons.

**Comment by roblillack** [comment]
Hey @Strahinja, this should be working now on the current `main`. Thanks for reporting!
