### ISSUE TITLE
No menu or ability to do anything with files

### ISSUE THREAD

**Issue by kbhors** [roblillack/fsviewer#6]
As title. I've installed it from source. I open FSViewer and the main window opens, I can browse the filesystem. 

Unfortunately, that's as far as it goes. The menu doesn't appear, and clicking on a file doesn't do anything. Right clicking doesn't do anything either.

Is there some dependency that makes the NeXT style menu work?

**Comment by roblillack** [comment]
The menu is only supported when WindowMaker is used as window manager. Do you run WindowMaker?

**Comment by kbhors** [comment]
Yes, i'm using WindowMaker. Is FSViewer trying to hook into it somehow?

I've used WindowMaker for many years and as far as I'm aware it doesn't offer any menu functionality to other software. Certainly it's not the approach GNUstep applications take.

**Comment by roblillack** [comment]
Oh, it does offer this functionality: WindowMaker will render these "app menus" based on some X resources the clients can set.

If the menus don't show for you, then this is most likely a well-known issue with the default configuration of WindowMaker on some distributions, please see https://github.com/roblillack/fsviewer/issues/4

**Comment by kbhors** [comment]
Okay, I have tried editing the WMWindowAttributes file in my user directory to match what's described there, and restarted windowmaker (actually, restarted whole machine).

Didn't make a lick of difference. I'm not sure why it would? It's just a prefs file for dock icons?

**Comment by kbhors** [comment]
Also, I noticed you have a fork of windowmaker that supposedly fixes this. I thought I'd try it.

Running ./configure && make && make install fails:

` /bin/sh ../libtool   --mode=install /usr/bin/install -c   libwraster.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libwraster.so.6.0.0 /usr/local/lib/libwraster.so.6.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libwraster.so.6.0.0': Permission denied
make[4]: *** [Makefile:534: install-libLTLIBRARIES] Error 1
make[4]: Leaving directory '/home/kyle/wmaker/wrlib'
make[3]: *** [Makefile:848: install-am] Error 2
make[3]: Leaving directory '/home/kyle/wmaker/wrlib'
make[2]: *** [Makefile:685: install-recursive] Error 1
make[2]: Leaving directory '/home/kyle/wmaker/wrlib'
make[1]: *** [Makefile:483: install-recursive] Error 1
make[1]: Leaving directory '/home/kyle/wmaker'
make: *** [Makefile:786: install] Error 2
`

No idea what the hell that's about. I gave it sudo too, no difference.

Tired of this fragile nonsense.

**Comment by roblillack** [comment]
Glad you were able to make it work & sorry that you're disappointed.

> Instead of using the systemwide file associations, it's using some clunky private database?

Please understand that this program was written before the XDG was even formed, so there was no such thing as "systemwide file associations" back then. 🤷
